#!/system/xbin/bash
#Tools Mr.Killer Versi :2.1
#Tools Berisi script yang tidak berbahaya
#Author : Mr.Killer dan Thunder killer

blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'                                        >
yellow='\033[33;1m'
sleep 1
echo ""
echo "\033[33;1m=======================================[>"
echo "\033[32;1mAuthor : Mr.Killer & Thunder killer"
echo "\033[35;1mTeam : Cyber Attacker Cirebon[!]"
echo "\033[33;1mKontak Me :  083120840944"
echo "\033[31;1mSubcribe Youtube:M4DN3SS GAMING"
echo "\033[33;1mUpload to git : None" "\033[32;1m&" "\033[3>"
echo "\033[34;1m[======================================[>"
sleep 1
echo ""
echo $green "Selamat Datang Pengguna"
echo $red "Di Tools versi ini telah banyak perubahan"
echo ""
echo "\033[32;1mSilahkan Pilih Tools Yang mau Kamu pake:)?>"
echo "\033[36;1m"
echo "[===============================================[>"
echo $green "1.> Spam Sms Tokopedia"
echo "[===============================================]>"
echo $purple "2.> Spam Sms Telkomnyet"
echo "[===============================================]>"
echo $cyan "3.> Spam Sms Matahari Mall"
echo "[===============================================]>"
echo $red "4.> Spam Sms HooqTV"
echo "[===============================================]>"
echo $white "5.> Spam Sms KFC"
echo "[===============================================]>"
echo $green "6.> Spam Sms PHD"
echo "[===============================================]>"
echo $purple "7.> Spam Sms Whiskas"
echo "[===============================================]>"
echo $cyan "8.> Spam Sms ZiPAY"
echo "[===============================================]>"
echo $red "9.> Nyari CC buat Carding"
echo "[===============================================]>"
echo $white "10.> Spam Akun Gmail"
echo "[===============================================]>"
echo $green "11.> Whois LookUp"
echo "[===============================================]>"
echo $purple "12.> Upload Admin Finder"
echo "[===============================================]>"
echo $cyan "13.> Script Deface Creator"
echo "[===============================================]>"
echo $red "14.> ReConDog Buat Information gathering"
echo "[===============================================]>"
echo $white "15.> Admin Login Finder"
echo "[===============================================]>"
echo $green "16.> Virus VbugMaker Creator"
echo "[===============================================]>"
echo $purple "17.> dowload script deface orang"
echo "[===============================================]>"
echo $cyan "18.> Autolike Facebook"
echo "[===============================================]>"
echo $red "19.> Facebook Auto_Reaction"
echo "[===============================================]>"
echo $white "20.> Bot Komentar Facebook"
echo "[===============================================]>"
echo $green "21.> Install txtool"
echo "[===============================================]>"
echo $purple "22.> install sqlscan"
echo "[===============================================]>"
echo $cyan "23.> install hash-buster"
echo "[===============================================]>"
echo $red "24.> Install Red_Hawk"
echo "[===============================================]>"
echo $white "25.> Install Torshammer buat DDOS website"
echo "[===============================================]>"
echo $green "26.> Install LITEDDOS buat DDOS website"
echo "[===============================================]>"
echo $purple "27.> Install Hunner Framework"
echo "[===============================================]>"
echo $cyan "28.> Install Sqlmap Buat Inject Situs"
echo "[===============================================]>"
echo $red "29.> Install 4wsectools"
echo "[===============================================]>"
echo $white "30.> Install Lazymux Buat Install Tools"
echo "[===============================================]>"
echo $green "31.> Mempercepat / Menstabilkan Jaringan/siny>"
echo "[===============================================]>"
echo $purple "32.> Mempercepat / menstabilkan jaringan 2"
echo "[===============================================]>"
echo $cyan "33.> Install BinGoo"
echo "[===============================================]>"
echo $red "34.> Full Bot Facebook"
echo "[===============================================]>"
echo $white "35.> Install Termux-A"
echo "[===============================================]>"
echo $green "36.> Install Tools GadoGado"
echo "[===============================================]>"
echo $purple "37.> Install Lazysqlmap"
echo "[==============================================]>"
echo $cyan "38.> Install tools diejoubu"
echo "[===============================================]>"
echo $red "39.> Install weeman Buat Phising"
echo "[===============================================]>"
echo $white "40.> Install iesDEFACE buat Deface Poc Webdav"
echo "[===============================================]>"
echo $green "41.> install errorcybertools"
echo "[===============================================]>"
echo $purple "42.> install A-Rat untuk Retas Android"
echo "[===============================================]>"
echo $cyan "43.> Scan-Website-Admin-Login"
echo "[===============================================]>"
echo $red "44.> DEFACE metode Webdav"
echo "[===============================================]>"
echo $white "45.> Tools Katoolin"
echo "[===============================================]>"
echo $green "46.> Main Tebak2 kan:v biar ga bt:v"
echo "[===============================================]>"
echo $purple "47.> Brute DEFACE webdav"
echo "[===============================================]>"
echo $cyan "48.> Browsing Di Termux"
echo "[===============================================]>"
echo $red "49.> Dengerin Lagu Youtube di Termux"
echo "[===============================================]>"
echo $white "50.> Tebak Tebak Kan Soal Cinta Tod"
echo "[===============================================]>"
echo $green "51.> Nuyul Bitcoin"
echo "[===============================================]>"
echo $purple "52.> Install MetaSploit"
echo "[===============================================]>"
echo $cyan "53.> MultiBrute Force Facebook Buat Hack Faceb>"
echo "[===============================================]>"
echo $red "54.> install WAScan"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "55.> install MultiSpam [Sms]"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $green "56.> Spam Sms Jd.id"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $purple "57.> DDOS xerxes"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "58.> IPGeoLocation Buat Lacak IP"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "59.> Install viSQL"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "60.> Install Kawai-Botnet Buat DDOS"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $green "61.> Install OWScan"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $purple "62.> Install AstraNmap"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "63.> Install Auxscan2.0"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "64.> Install Black-Hydra"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "65.> Install Ipddos"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $green "66.> Install hasher"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $purple "67.> Install PhisingGame Buat Hack ML & COC"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "68.> Kumpulan Tutorial Termux"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "69.> Chating Di Termux"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "70.> Cari Panel Login Admin Pakai Breacer"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $green "71.> Install SocialFish Buat Phising"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $purple "72.> Install MoonBuggy Buat Main Game"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "73.> Install Cupp Buat Worldlist Tertarget"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "74.> Install Hydra"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "75.> Install md5-crack"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>""
echo $green "76.> Install LITESPAM Buat Spam"
echo"[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $purple "77.> Mulung Bitcoin"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "78.> Install Ko-Dork"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "79.> Lihat Spesifikasi Ponsel"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "80.> install lhst"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $green "81.> Install The Fat Rat"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $purple "82.> Install CMSmap"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "83.> Install Kali Ubuntu"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "84.> Eror"
echo $yelow "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "85.> Install Brute Force Gmail"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $green "86.> Install Lokomedia Exploiters"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $purple "87.> Install Kali Linux Nethunter"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "88.> Install joomscan"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "89.> Install VulnScaner"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "90.> Install HN-Installer"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $green "91.> Install Fucking-Rat"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "92.> Install linux fedora"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "93.> Install information Gathering"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $blue "94.> Install ezsploit [Harus Root]"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $white "95.> Install Dirsearch "
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $red "96.> Install honeypot"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $cyan "97.> Install Killr"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $blue "98.> Install Human_Level_Control"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $green "99.> Install Termux-Mpv"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $purple "100.> Install OWASP-Nettacker"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo $yellow "0.> keluar"
echo "[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]>"
echo "\033[32;1m"
read -p "[Pillih-yang-kamu-inginkan]:~#" bro

